export const GET_FEED_CONTENT = 'GET_FEED_CONTENT';
export const GET_FEED_CONTENT_SUCCESS = 'GET_FEED_CONTENT_SUCCESS';

export const GET_MORE_FEED_CONTENT = 'GET_MORE_FEED_CONTENT';
export const GET_MORE_FEED_CONTENT_SUCCESS = 'GET_MORE_FEED_CONTENT_SUCCESS';

export const GET_USER_FEED_CONTENT = 'GET_USER_FEED_CONTENT';
export const GET_USER_FEED_CONTENT_SUCCESS = 'GET_USER_FEED_CONTENT_SUCCESS';

export const GET_MORE_USER_FEED_CONTENT = 'GET_MORE_USER_FEED_CONTENT';
export const GET_MORE_USER_FEED_CONTENT_SUCCESS = 'GET_MORE_USER_FEED_CONTENT_SUCCESS';
