
export default {
  steemit: 'gold',
  smooth: 'gold',
  cass: 'silver',
  bhuz: 'silver',
  liondani: 'bronze',
  donkeypong: 'bronze',
  furion: 'bronze',
  steemship: 'bronze',
  theprophet0: 'bronze',
  pfunk: 'bronze',
  deanliu: 'bronze',
  teamsteem: 'bronze',
  hanshotfirst: 'bronze',
  exyle: 'bronze',
  fulltimegeek: 'bronze',
  shortcut: 'bronze',
  hql2016: 'bronze',
  sweetsssj: 'bronze',
};
