
export default {
  steemit: 'platinum',
  smooth: 'gold',
  jamesc: 'gold',
  cass: 'gold',
  bhuz: 'silver',
  liondani: 'bronze',
  donkeypong: 'bronze',
  furion: 'bronze',
  steemship: 'bronze',
  theprophet0: 'bronze',
  pfunk: 'bronze',
  deanliu: 'bronze',
  teamsteem: 'bronze',
  hanshotfirst: 'bronze',
  exyle: 'bronze',
  fulltimegeek: 'bronze',
  shortcut: 'bronze',
  hql2016: 'bronze',
  sweetsssj: 'bronze',
  'craig-grant': 'bronze',
  twinner: 'bronze',
  beers: 'bronze',
  shaka: 'bronze',
  andu: 'bronze',
  ourlifestory: 'bronze',
  'delegate.lafona': 'bronze',
  joshbreslauer: 'bronze',
  aizensou: 'bronze',
  rubenalexander: 'bronze',
  roelandp: 'bronze',
  stellabelle: 'bronze',
  pnc: 'bronze',
};
