export const SUPPORTED_LANGUAGES = {
  'en-US': { longName: 'English', shortName: 'English' },
  'id-ID': { longName: 'Bahasa Indonesia - Indonesian', shortName: 'Bahasa Indonesia' },
  'ms-MY': { longName: 'Bahasa Melayu - Malay', shortName: 'Bahasa Melayu' },
  'ca-ES': { longName: 'Català - Catalan', shortName: 'Català' },
  'cs-CZ': { longName: 'Čeština - Czech', shortName: 'Čeština' },
  'da-DK': { longName: 'Dansk - Danish', shortName: 'Dansk' },
  'de-DE': { longName: 'Deutsch - German', shortName: 'Deutsch' },
  'et-EE': { longName: 'Eesti - Estonian', shortName: 'Eesti' },
  'es-ES': { longName: 'Español - Spanish', shortName: 'Español' },
  'fil-PH': { longName: 'Filipino', shortName: 'Filipino' },
  'fr-FR': { longName: 'Français - French', shortName: 'Français' },
  'hr-HR': { longName: 'Hrvatski - Croatian', shortName: 'Hrvatski' },
  'it-IT': { longName: 'Italiano - Italian', shortName: 'Italiano' },
  'hu-HU': { longName: 'Magyar - Hungarian', shortName: 'Magyar' },
  'nl-NL': { longName: 'Nederlands - Dutch', shortName: 'Nederlands' },
  'no-NO': { longName: 'Norsk - Norwegian', shortName: 'Norsk' },
  'pl-PL': { longName: 'Polski - Polish', shortName: 'Polski' },
  'pt-BR': { longName: 'Português - Portuguese', shortName: 'Português' },
  'ro-RO': { longName: 'Română - Romanian', shortName: 'Română' },
  'sl-SI': { longName: 'Slovenščina - Slovenian', shortName: 'Slovenščina' },
  'sv-SE': { longName: 'Svenska - Swedish', shortName: 'Svenska' },
  'vi-VN': { longName: 'Tiếng Việt - Vietnamese', shortName: 'Tiếng Việt' },
  'tr-TR': { longName: 'Türkçe - Turkish', shortName: 'Türkçe' },
  'yo-NG': { longName: 'Yorùbá - Yoruba', shortName: 'Yorùbá' },
  'el-GR': { longName: 'Ελληνικά - Greek', shortName: 'Ελληνικά' },
  'bg-BG': { longName: 'Български език - Bulgarian', shortName: 'Български език' },
  'ru-RU': { longName: 'Русский - Russian', shortName: 'Русский' },
  'uk-UA': { longName: 'Українська мова - Ukrainian', shortName: 'Українська мова' },
  'he-IL': { longName: 'עִבְרִית - Hebrew', shortName: 'עִבְרִית' },
  'ar-SA': { longName: 'العربية - Arabic‏', shortNameP: 'العربية' },
  'ne-NP': { longName: 'नेपाली - Nepali', shortName: 'नेपाली' },
  'hi-IN': { longName: 'हिन्दी - Hindi', shortName: 'हिन्दी' },
  'as-IN': { longName: 'অসমীয়া - Assamese', shortName: 'অসমীয়া' },
  'bn-IN': { longName: 'বাংলা - Bengali', shortName: 'বাংলা' },
  'ta-IN': { longName: 'தமிழ் - Tamil', shortName: 'தமிழ்' },
  'lo-LA': { longName: 'ພາສາລາວ - Lao', shortName: 'ພາສາລາວ' },
  'th-TH': { longName: 'ภาษาไทย - Thai', shortName: 'ภาษาไทย' },
  'ko-KR': { longName: '한국어 - Korean', shortName: '한국어' },
  'ja-JP': { longName: '日本語 - Japanese', shortName: '日本語' },
  'zh-CN': { longName: '简体中文 - Simplified Chinese', shortName: '简体中文' },
  // zh: '繁體中文 - Traditional Chinese',
};

export default null;
