module.exports = {
	// Auth
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	// App
	CONFIG_REQUEST: 'CONFIG_REQUEST',
	CONFIG_SUCCESS: 'CONFIG_SUCCESS',
	CONFIG_FAILURE: 'CONFIG_FAILURE',
	
	// Header
	SET_MENU: 'SET_MENU',

	// Sidebar
	SHOW_SIDEBAR: 'SHOW_SIDEBAR',
	HIDE_SIDEBAR: 'HIDE_SIDEBAR',
};