module.exports = {
	// App
	CONFIG_REQUEST: 'CONFIG_REQUEST',
	CONFIG_SUCCESS: 'CONFIG_SUCCESS',
	CONFIG_FAILURE: 'CONFIG_FAILURE',
	
	// Header
	SET_MENU: 'SET_MENU',

	// Sidebar
	SHOW_SIDEBAR: 'SHOW_SIDEBAR',
	HIDE_SIDEBAR: 'HIDE_SIDEBAR',
};
