module.exports = {
	// Auth
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	
	// Modal
	SHOW_MODAL: 'SHOW_MODAL',
	HIDE_MODAL: 'HIDE_MODAL',
	
	// Quicksart
	SET_TITLE: 'SET_TITLE',
	SET_ICON: 'SET_ICON',

	// Report
	REPORT_REQUEST: 'REPORT_REQUEST',
	REPORT_SUCCESS: 'REPORT_SUCCESS',

	// Entry
	ENTRY_REQUEST: 'ENTRY_REQUEST',
	ENTRY_SUCCESS: 'ENTRY_SUCCESS',
	
	// Save Entry
	SAVE_REQUEST: 'ENTRY_REQUEST',
	SAVE_SUCCESS: 'ENTRY_SUCCESS',

	// Tabs
	TAB_CREATE: 'TAB_CREATE',
	TAB_DELETE: 'TAB_DELETE',
	
	// Header
	SET_RANGE: 'SET_RANGE',
	REFRESH: 'REFRESH',
	SEARCH: 'SEARCH',
	SET_MENU: 'SET_MENU'
};