import request from 'superagent';
import Promise from 'bluebird';

export const initPushpad = (uid, username, token) => {
  const { PUSHPAD_PROJECT_ID, BUSYPUSH_ENDPOINT } = process.env;

  if (!(window && window.Worker)) { // eslint-disable-line
    return;
  }

  request
    .post(BUSYPUSH_ENDPOINT + '/api/getSignature')
    .send({
      uid,
      username,
      token
    })
    .end((err, res) => {
      if (err) {
        console.log(err);
        return;
      }

      if (res.body && res.body.isValid) {
        const { signatureId } = res.body;

        // sorry for uglified code, generated by pushpad
        /* eslint-disable */
        (function(p,u,s,h,x){p.pushpad=p.pushpad||function(){(p.pushpad.q=p.pushpad.q||[]).push(arguments)};h=u.getElementsByTagName('head')[0];x=u.createElement('script');x.async=1;x.src=s;h.appendChild(x);})(window,document,'https://pushpad.xyz/pushpad.js');

        pushpad('init', PUSHPAD_PROJECT_ID);
        pushpad('uid', `${uid}`, signatureId);
        pushpad('subscribe');
        /* eslint-enable */
      }
    });
};
