export const BENEFICIARY_ACCOUNT = 'busy.org';
export const BENEFICIARY_PERCENT = 1000;
export const REFERRAL_PERCENT = 1000;
export const MAX_TAG = 12; // to support SCOT tokens. but some Steem API may not work properly for more than 5 tags.
export const USER_METADATA_KEY = 'user_metadata'; // key for localStorage

// to support total past payout including beneficiaires: https://github.com/busyorg/busy/issues/2220
// Expected HF21 time: https://github.com/steemit/steem/blob/master/libraries/protocol/hardfork.d/0_21.hf
export const HF21_TIME = '2019-08-27T15:00:00';
export const DEFAULT_CURATION_REWARD_PERCENT = 25;
export const HF21_CURATION_REWARD_PERCENT = 50;

export const knownDomains = [
  'busy.org',
  'staging.busy.org',
  'steemit.com',
  'steem.io',
  'd.tube',
  'coinmarketcap.com',
  'youtube.com',
];

export const people = [
  'steemsports',
  'knozaki2015',
  'gavvet',
  'krnel',
  'papa-pepper',
  'ozchartart',
  'craig-grant',
  'ericvancewalton',
  'curie',
  'stellabelle',
  'doitvoluntarily',
  'sirwinchester',
  'sweetsssj',
  'kevinwong',
  'jrcornel',
  'thecryptofiend',
  'steemcleaners',
  'kingscrown',
  'opheliafu',
  'officialfuzzy',
  'steemtrail',
  'good-karma',
  'dollarvigilante',
  'sauravrungta',
  'chinadaily',
  'calaber24p',
  'kaylinart',
  'dantheman',
  'tuck-fheman',
  'mynameisbrian',
  'macksby',
  'hanshotfirst',
  'hilarski',
  'ats-david',
  'fyrstikken',
  'alexbeyman',
  'gringalicious',
  'donkeypong',
  'steempower',
  'marius19',
  'mindhunter',
  'the-alien',
  'kafkanarchy84',
  'dwinblood',
  'stephenkendal',
  'luzcypher',
  'pfunk',
  'oflyhigh',
  'dana-edwards',
  'cryptoctopus',
  'steemvoter',
  'myfirst',
  'elfkitchen',
  'barrydutton',
  'dragosroua',
  'jlufer',
  'acidyo',
  'timsaid',
  'timcliff',
  'lukestokes',
  'lily-da-vine',
  'meesterboom',
  'infovore',
  'klye',
  'charlieshrem',
  'rok-sivante',
  'ausbitbank',
  'everittdmickey',
  'homeartpictures',
  'birds90',
  'michelle.gent',
  'tamim',
  'clayop',
  'terrycraft',
  'b0y2k',
  'dragonslayer109',
  'heiditravels',
  'joseph',
  'ace108',
  'kus-knee',
  'gardenofeden',
  'cryptogee',
  'deanliu',
  'anwenbaumeister',
  'jamtaylor',
  'daveks',
  'masteryoda',
  'onceuponatime',
  'halo',
  'ash',
  'englishtchrivy',
  'penguinpablo',
  'yoonjang0707',
  'jerrybanfield',
  'cheetah',
  'bridgetbunchy',
  'gargon',
  'ocrdu',
  'nanzo-scoop',
  'surfermarly',
  'blockchainstudio',
  'steemfinex',
];
